version: '3.8'

services:
  nginxapp:
    image: nginxapp 
    ports:
      - "80:80"  
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf  
    networks:
      - nginx-network

  python_app:
    image: python_app 
    container_name: python_app
    expose:
      - "8000"  
    networks:
      - nginx-network

networks:
  nginx-network:
    driver: bridge  
